name: Run GitHub Job Daily

on:
  schedule:
    - cron: '0 2 * * *' # This runs the job every day at 2:00 AM UTC
  workflow_dispatch: # Allows manual triggering of the workflow from the GitHub interface

jobs:
  run-github-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml spacy selenium pandas sqlalchemy pymysql webdriver-manager

      - name: Run github_job.py
        run: |
          python github_job.py
