name: Run Automation Script

on:
  schedule:
    - cron: '0 */4 * * *'  # Runs every 4 hours

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Replace '3.x' with the version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have dependencies listed in requirements.txt

    - name: Run Python script
      run: python github_job.py
